mysite/blogarea/urls.py
from tkinter.font import names

from django.urls import path
from . import views
from .views import BlogHome, ArticleDetailView, AddPostView, ShowProfileView, UpdatePostView,  CategoriesView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", BlogHome.as_view(), name="blogarea"),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name="ArticleDetailView"),
    path('writeYourBlog/',AddPostView.as_view(),name="writeYourBlog"),
    path('article/updateBlog/<int:pk>',views.UpdatePostView,name="updateBlog"),
    path('article/deleteBlog/<int:pk>', views.deleteBlog, name="deleteBlog"),
    path('category/<str:cats>',views.CategoryView,name='category'),
    path('likes/<int:pk>',views.LikeView,name='like_post'),
    path('show_profile_page/<int:pk>/',ShowProfileView.as_view(),name="show_profile_page"),
    path('load-more/',views.load_more,name="load-more"),
    path('filtered_load_more/',views.filtered_load_more,name="filtered_load_more"),
    path('submit_comment/',views.submit_comment,name="submit_comment"),
    path('answer/',views.answer,name="answer"),
    path('categories/',CategoriesView.as_view(),name="categories_list"),
    path('categories/<str:tag>/',views.CategoryView,name="categories_detail"),
    path('search/',views.search,name="search"),
    path('searchresult/',views.searchresult,name="searchresult"),
    path('random-post/',views.random_post,name="random-post"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/core/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.home,name='home'),
]

mysite/mysite/urls.py
import django
from django.contrib import admin
import django.contrib
import django.contrib.auth
import django.contrib.auth.urls
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('authentication/', include('authentication.urls')),
    path('blogarea/', include('blogarea.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("tailwind/",include("tailwindcode.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blogarea/models.py
from ast import mod
from os import name, truncate
from tabnanny import verbose
from tkinter import CASCADE
from turtle import position
from django.db import models
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import reverse
from datetime import datetime,date
from ckeditor.fields import RichTextField
from django.utils.html import strip_tags
from phonenumber_field.modelfields import PhoneNumberField
from requests import post

class Category(models.Model):
    name = models.CharField(max_length=255,default="Uncategorized")
    about = models.CharField(max_length=255,default="Lorem ipsum dolor sit amet consectetur adipisicing elit.!")
    image = models.ImageField(upload_to='category/',null=True,blank=True, default='thumbnail/thumbnail.jpg')
    def __str__(self):
        return self.name
    
    def get_absoulte_url(self):
        return reverse('ArticleDetailView', args=[self.id])
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class Post(models.Model):
    
    choices = Category.objects.all().values_list('name','name')
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    post_date = models.DateField(auto_now_add=True)
    hashtags = models.TextField(max_length=200,null=True)
    category = models.CharField(choices=choices,max_length=255,default="Uncategorized")
    articleSnippet = models.CharField(max_length=50)
    thumbnail = models.ImageField(upload_to='thumbnail/',null=True,blank=True, default='thumbnail/thumbnail.jpg')
    like = models.ManyToManyField(User,related_name='blog_posts',null=True,blank=True)
    tags = models.ManyToManyField("Hashtag",related_name="posts",null=True,blank=True)
    body = RichTextField(blank=True,null=True)
    
    def total_likes(self):
        return self.like.count()
    
    def word_count(self):
        text_content = strip_tags(self.body)
        return len(text_content.split())

    def __str__(self):
        return self.title + ' | ' +  str(self.author)

    def get_absolute_url(self):
            return reverse('ArticleDetailView', args=[self.id])
        



class Profile(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    profileImage = models.ImageField(upload_to='profile_pics',null=True,blank=True,default="profile_pics/default_profile_pic.jpg")
    profileBackground = models.ImageField(upload_to='profile_background',null=True,blank=True)
    bio = models.TextField()
    blogcaption = models.CharField(max_length=150,null=True,blank=True,default="Former Adventurer turned full-time Dad moonlighting as an author")
    contact = PhoneNumberField(blank=True, null=True)
    location = models.CharField(max_length=150,null=True,blank=True,default="Earth")
    occupation = models.CharField(max_length=50,null=True,blank=True,default="Occupation")
    industry = models.CharField(max_length=50,null=True,blank=True,default="Industry")
    position = models.CharField(max_length=50,null=True,blank=True,default="position")
    skills = models.TextField(null=True,blank=True,help_text="Enter your skills separated by commas")
    education = models.TextField(null=True,blank=True)
    twitter_link = models.URLField(max_length=200,null=True,blank=True,default="https://x.com/")
    instagram_link = models.URLField(max_length=200,null=True,blank=True,default="https://instagram.com/")
    youtube_link = models.URLField(max_length=200,null=True,blank=True,default="https://youtube.com/")

    def __str__(self):
        return str(self.user)

    def total_posts(self):
        return self.user.post_set.count()
class Comment(models.Model):
    post = models.ForeignKey(Post,null=True,on_delete=models.CASCADE,related_name='comments')
    user = models.ForeignKey(User,null=True,on_delete=models.CASCADE)
    body = models.TextField()
    comment_date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User,related_name='liked_comment',blank=True,default=0)
    dislikes = models.ManyToManyField(User,related_name='disliked_comment',blank=True)
    
    def __str__(self):
        return f"{self.post.title} - {self.user.username} - {self.body[:25]}"
    
    def total_likes(self):
        return self.likes.count()
    
    def total_dislikes(self):
        return self.dislikes.count()
    
class Reply(models.Model):
    user = models.ForeignKey(User,null=True,on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment,null=True,on_delete=models.CASCADE)
    body = models.TextField()
    reply_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User,related_name='liked_reply',blank=True)
    dislikes = models.ManyToManyField(User,related_name='disliked_reply',blank=True)
    
    def __str__(self):
        return f"{self.user} - {self.comment | truncate:20}"
    
    def total_likes(self):
        return self.likes.count()
    
    def total_dislikes(self):
        return self.dislikes.count()
    
class Hashtag(models.Model):
    tag = models.CharField(max_length = 20,null=True,blank=True)
    post = models.ManyToManyField(Post,null=True,related_name='hashtag_posts')
    
    def __str__(self):
        return self.tag
    
    def get_posts(self):
        return self.post.all()
    
    
    
    

mysite/blogarea/views.py
from multiprocessing import context
import random
from sre_constants import SUCCESS
from unicodedata import category
from urllib import request, response
from wsgiref.util import request_uri
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth import logout,authenticate 
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from requests import post
from .models import Category, Comment, Hashtag, Post, Profile
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect , StreamingHttpResponse
from django.db.models import Count,Q
from blogarea.models import Profile
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import CommentForm, PostForm
from django.views.generic.edit import FormMixin
from openai import OpenAI
import google.generativeai as genai
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse
from .models import Post, Hashtag
from .forms import PostForm
from django.conf import settings
# Create your views here.
class BlogHome(ListView):
    model = Post
    template_name = 'blogHome.html'
    ordering = ['post_date']
    
    def get_context_data(self, **kwargs):
        context = super(BlogHome, self).get_context_data(**kwargs)
        #annotate is used to add extra field to each object without saving it to databse just for sorting or calculation purposes
        posts = Post.objects.annotate(like_count=Count('like')).order_by('-like_count')
        
        post_with_highest_likes = posts.first()  # The post with the highest likes
        post_with_second_highest_likes = posts[1] if len(posts) > 1 else None  # The second post, if it exists
        post_with_third_highest_likes = posts[2] if len(posts) > 2 else None  # The third post, if it exists
        post_with_fourth_highest_likes = posts[3] if len(posts) > 3 else None  # The fourth post, if it exists
        non_featured_post = posts.exclude(id__in=[post_with_highest_likes.id,
                                                  post_with_second_highest_likes.id,
                                                  post_with_third_highest_likes.id,
                                                  post_with_fourth_highest_likes.id,]
                                          )

    # Add posts to context
        context['posts'] = non_featured_post[:9]
        context['post_with_highest_likes'] = post_with_highest_likes
        context['post_with_second_highest_likes'] = post_with_second_highest_likes
        context['post_with_third_highest_likes'] = post_with_third_highest_likes
        context['post_with_fourth_highest_likes'] = post_with_fourth_highest_likes
    
        return context
    
class ArticleDetailView(DetailView,FormMixin):
    model = Post
    template_name = 'article_Detail.html'
    form_class = CommentForm
    
    def get_context_data(self, *args, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(*args, **kwargs)
        posts = Post.objects.annotate(like_count=Count('like')).order_by('-like_count')
        current_post = get_object_or_404(Post,id=self.kwargs['pk'])
        related_posts = posts.filter(Q(category=current_post.category) | Q(tags__tag__in=current_post.tags.all()) ).exclude(id=current_post.id)
        total_words = current_post.word_count()
        total_likes = current_post.total_likes()
        has_liked = self.request.user in current_post.like.all() if self.request.user.is_authenticated else False 
        comments = Comment.objects.filter(post_id = current_post.id)
        comments_number = comments.count()
            
        context['current_post'] = current_post
        context['comments_number'] = comments_number
        context['comments'] =  list(comments.filter(user=self.request.user)) + list(comments.exclude(user=self.request.user).order_by('-comment_date')) if self.request.user.is_authenticated else list(comments)
        context['form'] = self.get_form()
        context['has_liked'] = has_liked
        context['related_posts'] = related_posts[:4]
        context['posts'] = posts
        context['total_likes'] = total_likes
        context['total_words'] = total_words
        return context       
    
    def post(self,request,*args,**kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.object 
            comment.user = self.request.user
            comment.save()
            return redirect('ArticleDetailView',pk=self.object.pk)
        return self.form_invalid(form) 
    
class ShowProfileView(DetailView):
    model = Profile
    template_name = 'showProfilePage.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super(ShowProfileView, self).get_context_data(*args, **kwargs)
        page_user = get_object_or_404(Profile,id=self.kwargs['pk'])
        posts = Post.objects.filter(author = page_user.user).order_by('-post_date')
        total_posts = Post.objects.filter(author=page_user.user).count()
        total_likes = Post.objects.filter(author=page_user.user).aggregate(total_likes=Count('like'))['total_likes'] or 0
        skills = page_user.skills.split(',') if page_user.skills else []
        education = page_user.education.split(',') if page_user.education else []
        show_load_more = True
        if posts.count()<4:
            show_load_more = False
        context['show_load_more'] = show_load_more
        context['posts'] = posts[:4]
        context['education'] = education
        context['skills'] = skills
        context['page_user'] = page_user
        context['total_posts'] = total_posts
        context['total_likes'] = total_likes
        
        return context    

class AddPostView(LoginRequiredMixin,CreateView):
    model = Post
    template_name = 'writeBlog.html'
    form_class = PostForm
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        
        # Process hashtags
        tags = form.instance.hashtags
        tags_list = [tag.strip().lstrip('#') for tag in tags.split(',') if tag.strip()]
        
        for tag in tags_list:
            hashtag, created = Hashtag.objects.get_or_create(tag=tag)
            hashtag.post.add(form.instance)
            form.instance.tags.add(hashtag)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('ArticleDetailView', kwargs={'pk': self.object.pk})

def CategoryView(request,tag):
    category_posts = Post.objects.filter(Q(tags__tag = tag) | Q(category = tag)).distinct()
    return render(request,'categories.html',{'posts':category_posts,'category':tag})

class CategoriesView(ListView):
    model = Hashtag
    template_name = "categoriesPage.html"
    context_object_name = "categories"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all()
        context["categories"] = Category.objects.all()
        return context
    
@login_required
def UpdatePostView(request, pk):
    post = get_object_or_404(Post, id=pk)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            #creating the object temporarily for manipulation
            post = form.save(commit=False) 
            post.tags.clear()
            
            if post.hashtags:
                tags_list = [tag.strip().lstrip('#') for tag in post.hashtags.split(',') if tag.strip()]
                for tag in tags_list:
                    hashtag, created = Hashtag.objects.get_or_create(tag=tag)
                    hashtag.post.add(post)
                    post.tags.add(hashtag)
                    
            #saving the object to DB after doing the manipulation
            post.save()
            messages.success(request, "Post has been updated successfully!")
            return redirect(reverse('ArticleDetailView', kwargs={'pk': post.pk}))
        else:
            messages.error(request, "There was an error in saving the post!")

    else:
        form = PostForm(instance=post)

    return render(request, 'updateBlog.html', {'form': form})

@login_required
def deleteBlog(request,pk):
    post = Post.objects.get(id=pk)
    if request.method == "POST":
        post.delete()
        messages.success(request,"Post has been deleted successfully !!")
        return redirect("blogarea")
    return redirect(reverse_lazy("blogarea"))

def logout_user(request):
    logout(request)
    messages.success(request,"You have logged out")
    return redirect('home')

def load_more(request):
    offset=int(request.POST.get('offset',False))
    limit=6
    posts=Post.objects.all()[offset:limit+offset]
        
    post_list = [
        {
            "id":post.id,
            "title":post.title,
            "articleSnippet":post.articleSnippet,
            "post_date":post.post_date,
            "thumbnail":request.build_absolute_uri(post.thumbnail.url)
                    if post.thumbnail
                    else 
                    request.build_absolute_uri('/media/thumbnail/thumbnail.jpg'),    
            "author":{
                "id":post.author.id,
                "username":post.author.username,
                "profile":{
                    "profile-id":post.author.profile.id,

mysite/blogarea/templates/blogHome.html
<!DOCTYPE html>
{% load static tailwind_tags %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% tailwind_css %}
    <link
      href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100..900;1,100..900&family=Exo+2:ital,wght@0,500;1,500&display=swap"
      rel="stylesheet"
    />
    {% load static %}
  </head>
  <body>
    {% include 'nav.html' %}
    <!-- prettier-ignore  -->
    {% if messages %}
    <div
      id="alert"
      class="bg-green-50 border-b border-green-400 text-green-800 text-sm p-4 flex justify-between"
    >
      <div>
        <div class="flex items-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-4 w-4 mr-2"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fill-rule="evenodd"
              d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
              clip-rule="evenodd"
            />
          </svg>
          <p>
            {% for message in messages %}
            <span class="font-bold">{{message}}</span>
            {% endfor %}
          </p>
        </div>
      </div>
      <div>
        <button
          onclick="document.getElementById('alert').style.display = 'none'"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>
    </div>
    {% endif %}
    <div class="flex justify-center">
      <div
        class="flex items-center justify-center flex-col lg:w-3/5 md:w-4/5 w-full px-5"
      >
        <div class="flex flex-col mb-10 relative w-full h-[700px] sm:h-[800px]">
          <div class="flex flex-col">
            <div class="flex justify-between">
              <div
                class="px-0 py-10 sm:px-10 font-semibold text-5xl sm:text-6xl w-2/5 sm:w-3/5"
                style="font-family: Bitter"
              >
                Blogs
              </div>
              <div
                class="pl-2 py-10 sm:px-10 sm:p-10 w-3/5 sm:w-2/5 text-xs sm:text-lg"
              >
                Stay informed with the latest updates, events, and announcements
                shaping the InkVara.com community and beyond
              </div>
            </div>
            <hr class="border-1 border-gray-300 mb-5" />
            <h1
              class="text-blue-600 font-roboto font-bold text-2xl mb-2 mt-0 lg:mt-6"
            >
              Featured
            </h1>
          </div>

          <div class="h-full">{% include 'carousel.html' %}</div>
        </div>

        <div class="w-full">
          <div class="w-full">
            <h1 style="font-family: Bitter" class="text-3xl font-medium">
              Discover
            </h1>
            <p class="text-gray-600 mb-4">
              Explore popular blogs that inspire, educate, and entertain.
            </p>
            <hr />
            <br />
          </div>
          <div
            id="cardContainer"
            class="grid grid-cols-1 md:grid-cols-3 sm:grid-cols-2 gap-8 w-full pb-10"
          >
            {% for post in posts%} {% include 'cards.html'%} {% endfor %}
          </div>
        </div>

        <button
          id="load-more"
          type="button"
          class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 p-5 w-[150px] my-10 rounded-xl"
        >
          Load More
        </button>
        {% include 'profile_card.html'%}
      </div>
    </div>
    {% include 'newsletter.html'%} {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>

    {% include 'load-more.html'%} {% include 'footerCode.html' %}
  </body>
</html>

mysite/blogarea/templates/cards.html
<div
  class="max-w-sm w-full shadow-md hover:scale-[1.05] transition-transform duration-300 flex flex-col"
>
  <!-- Image Section -->
  <div
    class="h-48 bg-cover rounded-t text-center overflow-hidden"
    style="background-image: url('{% if post.thumbnail %}{{ post.thumbnail.url }}{% else %}/media/thumbnail/thumbnail.jpg{% endif %}')"
    title="{{ post.title }}"
  ></div>

  <!-- Content Section -->
  <div
    class="blog-cards border border-gray-300 bg-white rounded-b p-4 flex flex-col justify-between flex-grow"
  >
    <div class="mb-4">
      <a href="{% url 'ArticleDetailView' post.id %}">
        <h3 class="text-gray-900 font-bold text-xl hover:text-cyan-600">
          {{ post.title }}
        </h3>
      </a>
      <p class="text-sm text-blue-600 font-semibold flex items-center mb-2">
        <!-- prettier-ignore -->
        {% for tag in post.tags.all|slice:":3" %} #{{tag.tag}}&nbsp;
                {% endfor %}
      </p>
      <p class="text-gray-700 text-sm line-clamp-3">
        {{ post.articleSnippet }}
      </p>
    </div>

    <!-- Author Section -->
    <div class="flex items-center">
      <a
        href="{% url 'show_profile_page' post.author.profile.id %}"
        class="flex items-center"
      >
        <img
          class="w-10 h-10 rounded-full mr-3"
          src="{% if post.author.profile.profileImage %}{{ post.author.profile.profileImage.url }}{% else %}/media/thumbnail/thumbnail.jpg{% endif %}"
          alt="Author Image"
        />
        <div class="text-sm">
          <p class="text-gray-900 font-semibold">{{ post.author }}</p>
          <p class="text-gray-600">{{ post.post_date }}</p>
        </div>
      </a>
    </div>
  </div>
</div>

mysite/blogarea/templates/categoriesPage.html
<!DOCTYPE html>
{% load static tailwind_tags %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
    {% tailwind_css %} {% load static %}
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100..900;1,100..900&family=Exo+2:ital,wght@0,500;1,500&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body class="min-h-screen flex flex-col">
    {% include 'nav.html'%}
    <div class="flex-1 px-5 md:px-32 py-10">
      <div>
        <h1 class="font-semibold text-5xl" style="font-family: bitter">
          Categories
        </h1>
        <hr class="border-1 border-slate-300 my-10" />
      </div>
      <div id="cardContainer" class="flex flex-wrap gap-8">
        <!-- prettier-ignore  -->
        {% for category in categories%} {% include 'categorycard.html'%} {% endfor %}
      </div>
    </div>

    {% include 'footerCode.html'%}
  </body>

  <script></script>
</html>

mysite/blogarea/templates/comment.html
<script>
  $("#comment-form").on("submit", function (e) {
    e.preventDefault();
    $.ajax({
      url: '{% url "submit_comment" %}',
      type: "POST",
      data: {
        post: "{{ current_post.id }}",
        body: $("#comment-text").val(), // Ensure this matches the ID of your comment input field
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      success: function (response) {
        if (response.success) {
          var comment = `
<div class="flex items-center space-x-2 md:space-x-4">
  <div class="flex flex-shrink-0 self-start cursor-pointer">
    <a href="${response.comment.profile_url}"><img
      src="${response.comment.profile_image}"
      alt=""
      class="h-8 w-8 md:h-12 md:w-12 object-cover rounded-full"
    /></a>
    
  </div>

  <div class="flex items-center justify-center space-x-2 md:space-x-3">
    <div class="block">
      <div class="bg-gray-100 w-auto rounded-xl px-2 py-2 md:px-4 md:py-3">
        <div class="font-medium text-sm md:text-lg">
          <a href="${response.comment.profile_url}" class="hover:underline">
            <small>${response.comment.user}</small>
          </a>
        </div>
        <div class="text-xs md:text-base">${response.comment.body}</div>
      </div>
      <div class="flex justify-start items-center text-xs md:text-sm w-full mt-1">
        <div class="font-semibold text-gray-700 px-2 md:px-3 flex items-center space-x-1 md:space-x-2">
          <a href="#" class="hover:underline">
            <strong><i class="bx bx-like"></i> Like - ${response.comment.comment_likes}</strong>
          </a>
          <a href="#" class="hover:underline">
            <strong><i class='bx bx-dislike' ></i> Dislike - ${response.comment.comment_dislikes}</strong>
          </a>
          <span class="self-center">·</span>
          <a href="#" class="hover:underline">
            <strong>💬 Reply</strong>
          </a>
          <span class="self-center">·</span>
          <a href="#" class="hover:underline">
            <strong>${response.comment.comment_date}</strong>
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="self-stretch flex justify-center items-center transform transition-opacity duration-200 opacity-0 hover:opacity-100">
    <a href="#">
      <div class="text-xs md:text-sm cursor-pointer flex h-6 w-6 md:h-8 md:w-8 transform transition-colors duration-200 hover:bg-gray-200 rounded-full items-center justify-center">
        <svg class="w-4 h-4 md:w-6 md:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
        </svg>
      </div>
    </a>
  </div>
</div>
`;

          $("#comments").append(comment);
          $("#id_body").val(""); // Clear the comment input field
        } else {
          alert("Error: " + response.error);
        }
      },
      error: function (xhr, status, error) {
        alert("An error occurred: " + error);
      },
    });
  });
</script>